#pragma once;
#include "../../Utils/GameModeConsts.h"
#include "../Map.h"
#include <vector>

namespace game_framework
{
	const vector<vector<int>> Level_5_zombie_instruction{
		// {zombie type, zombie time to spawn in seconds, zombie row pos, zombie has spawned}
		// Normal, flag, newspaper, cone & buckethead

		// starting stream
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 30, 1, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 50, 0, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 70, 2, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 90, 0, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 110, 1, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NEWSPAPER, 130, 1, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 131, 1, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::CONEHEAD, 132, 0, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 150, 3, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 151, 4, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::WAVE_CHKPOINT, 180, 0, 0},

		// middle wave
		{(int)ZOMBIE_INSTRUCTION_TYPE::FLAG, 180, 0, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 182, 0, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::CONEHEAD, 184, 0, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 186, 0, 0},

		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 180, 1, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::BUCKETHEAD, 182, 1, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 184, 1, 0},

		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 180, 2, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 182, 2, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 184, 2, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 186, 2, 0},

		{(int)ZOMBIE_INSTRUCTION_TYPE::NEWSPAPER, 180, 3, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 182, 3, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 184, 3, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 186, 3, 0},

		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 180, 4, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 182, 4, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 184, 4, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 186, 4, 0},

		{(int)ZOMBIE_INSTRUCTION_TYPE::WAIT, 220, 0, 0},

		// in-between stream
		{(int)ZOMBIE_INSTRUCTION_TYPE::CONEHEAD, 250, 3, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NEWSPAPER, 250, 0, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 250, 3, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::CONEHEAD, 280, 1, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::BUCKETHEAD, 280, 3, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NEWSPAPER, 300, 1, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 300, 1, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::CONEHEAD, 300, 0, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 300, 0, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::CONEHEAD, 300, 4, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::WAVE_CHKPOINT, 320, 0, 0},

		// final wave

		{(int)ZOMBIE_INSTRUCTION_TYPE::CONEHEAD, 340, 0, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 342, 0, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NEWSPAPER, 344, 3, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 346, 3, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 348, 3, 0},

		{(int)ZOMBIE_INSTRUCTION_TYPE::FLAG, 340, 1, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::CONEHEAD, 342, 1, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 344, 1, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NEWSPAPER, 346, 3, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 348, 3, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 350, 3, 0},

		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 340, 2, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NEWSPAPER, 342, 2, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::BUCKETHEAD, 344, 2, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 346, 3, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 348, 3, 0},

		{(int)ZOMBIE_INSTRUCTION_TYPE::NEWSPAPER, 340, 3, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 342, 3, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::CONEHEAD, 344, 3, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 346, 3, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 348, 3, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 350, 3, 0},

		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 340, 4, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::BUCKETHEAD, 340, 4, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::CONEHEAD, 340, 4, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 340, 3, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 340, 3, 0},
	};

	const string LEVEL_5_MSG_BITMAP = "Resources/Background/Level Up/BMP/Level1-5.bmp";

	class Level5 : public Map
	{
	public:
		Level5() : Map(Level_5_zombie_instruction, LEVEL_5_MSG_BITMAP, true) {};

		~Level5() {};

	protected:
		int getPreviousLevel() { return LEVEL_4; }
		int getCurrentLevel() { return LEVEL_5; }
		int getNextLevel() { return LEVEL_6; }
	};

}