#pragma once;
#include "../../Utils/GameModeConsts.h"
#include "../Map.h"
#include <vector>

namespace game_framework
{
	const vector<vector<int>> Level_10_zombie_instruction{
		// {zombie type, zombie time to spawn in seconds, zombie row pos, zombie has spawned}
		// Normal, flag, newspaper, cone & buckethead

		// starting stream
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 30, 4, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 50, 0, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 70, 2, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 90, 2, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 110, 1, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NEWSPAPER, 130, 0, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 131, 2, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::CONEHEAD, 132, 3, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 150, 3, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 151, 0, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::WAVE_CHKPOINT, 180, 0, 0},

		// middle wave
		{(int)ZOMBIE_INSTRUCTION_TYPE::BUCKETHEAD, 180, 0, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 182, 0, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 184, 0, 0},

		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 180, 1, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 182, 1, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 184, 1, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 186, 1, 0},

		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 180, 2, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 182, 2, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 184, 2, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 186, 2, 0},

		{(int)ZOMBIE_INSTRUCTION_TYPE::FLAG, 180, 3, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NEWSPAPER, 180, 3, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 182, 3, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 184, 3, 0},

		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 180, 4, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::CONEHEAD, 182, 4, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 184, 4, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 186, 4, 0},

		{(int)ZOMBIE_INSTRUCTION_TYPE::WAIT, 220, 0, 0},

		// in-between stream
		{(int)ZOMBIE_INSTRUCTION_TYPE::CONEHEAD, 250, 4, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NEWSPAPER, 250, 3, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 250, 3, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::CONEHEAD, 280, 2, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::BUCKETHEAD, 280, 1, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NEWSPAPER, 300, 2, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 300, 2, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::CONEHEAD, 300, 0, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 300, 4, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::CONEHEAD, 330, 4, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::WAVE_CHKPOINT, 340, 0, 0},

		// second wave
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 390, 0, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NEWSPAPER, 392, 0, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::BUCKETHEAD, 394, 0, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 396, 0, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 398, 0, 0},

		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 390, 1, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::CONEHEAD, 392, 1, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 394, 1, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NEWSPAPER, 396, 3, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 398, 3, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 390, 3, 0},

		{(int)ZOMBIE_INSTRUCTION_TYPE::CONEHEAD, 390, 2, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::FLAG, 390, 2, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NEWSPAPER, 394, 2, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 396, 2, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 398, 2, 0},

		{(int)ZOMBIE_INSTRUCTION_TYPE::NEWSPAPER, 390, 3, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 392, 3, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::CONEHEAD, 394, 3, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 396, 3, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 398, 3, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 400, 3, 0},

		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 390, 4, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::BUCKETHEAD, 392, 4, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::CONEHEAD, 394, 4, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 396, 3, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 398, 3, 0},

		{(int)ZOMBIE_INSTRUCTION_TYPE::WAIT, 410, 0, 0},

		// in-between stream
		{(int)ZOMBIE_INSTRUCTION_TYPE::BUCKETHEAD, 440, 1, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::CONEHEAD, 440, 3, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 440, 4, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::CONEHEAD, 470, 1, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::BUCKETHEAD, 470, 0, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NEWSPAPER, 500, 2, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 500, 0, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::CONEHEAD, 500, 2, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 500, 0, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::CONEHEAD, 520, 3, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::WAVE_CHKPOINT, 530, 0, 0},


		// FINALE wave
		{ (int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 560, 0, 0 },
		{ (int)ZOMBIE_INSTRUCTION_TYPE::NEWSPAPER, 562, 0, 0 },
		{ (int)ZOMBIE_INSTRUCTION_TYPE::CONEHEAD, 564, 0, 0 },
		{ (int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 566, 0, 0 },
		{ (int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 568, 0, 0 },
		{ (int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 570, 0, 0 },

		{ (int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 560, 1, 0 },
		{ (int)ZOMBIE_INSTRUCTION_TYPE::BUCKETHEAD, 562, 1, 0 },
		{ (int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 564, 1, 0 },
		{ (int)ZOMBIE_INSTRUCTION_TYPE::CONEHEAD, 566, 3, 0 },
		{ (int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 568, 3, 0 },
		{ (int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 560, 3, 0 },

		{ (int)ZOMBIE_INSTRUCTION_TYPE::BUCKETHEAD, 560, 2, 0 },
		{ (int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 560, 2, 0 },
		{ (int)ZOMBIE_INSTRUCTION_TYPE::CONEHEAD, 564, 2, 0 },
		{ (int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 566, 2, 0 },
		{ (int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 568, 2, 0 },

		{ (int)ZOMBIE_INSTRUCTION_TYPE::NEWSPAPER, 560, 3, 0 },
		{ (int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 562, 3, 0 },
		{ (int)ZOMBIE_INSTRUCTION_TYPE::BUCKETHEAD, 564, 3, 0 },
		{ (int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 566, 3, 0 },
		{ (int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 568, 3, 0 },

		{ (int)ZOMBIE_INSTRUCTION_TYPE::FLAG, 560, 4, 0 },
		{ (int)ZOMBIE_INSTRUCTION_TYPE::BUCKETHEAD, 562, 4, 0 },
		{ (int)ZOMBIE_INSTRUCTION_TYPE::CONEHEAD, 564, 4, 0 },
		{ (int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 566, 3, 0 },
		{ (int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 568, 3, 0 },
	};

	const string LEVEL_10_MSG_BITMAP = "Resources/Background/Level Up/BMP/Level2-5.bmp";

	class Level10 : public Map
	{
	public:
		Level10() : Map(Level_10_zombie_instruction, LEVEL_10_MSG_BITMAP, false) {};

		~Level10() {};

	protected:
		int getPreviousLevel() { return LEVEL_9; }
		int getCurrentLevel() { return LEVEL_10; }
		int getNextLevel() { return MENU_BTN; }
	};

}