#pragma once;
#include "../../Utils/GameModeConsts.h"
#include "../Map.h"
#include <vector>

namespace game_framework
{
	const vector<vector<int>> Level_10_zombie_instruction{
		// {zombie type, zombie time to spawn in seconds, zombie row pos, zombie has spawned}
		// Normal, flag, newspaper, cone & buckethead

		// starting stream
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 30, 1, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 50, 0, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 70, 2, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 90, 0, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 110, 1, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NEWSPAPER, 130, 1, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 131, 1, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::CONEHEAD, 132, 0, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 150, 3, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 151, 4, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::WAVE_CHKPOINT, 180, 0, 0},

		// middle wave
		{(int)ZOMBIE_INSTRUCTION_TYPE::FLAG, 180, 0, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 182, 0, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::CONEHEAD, 184, 0, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 186, 0, 0},

		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 180, 1, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::BUCKETHEAD, 182, 1, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 184, 1, 0},

		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 180, 2, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 182, 2, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 184, 2, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 186, 2, 0},

		{(int)ZOMBIE_INSTRUCTION_TYPE::NEWSPAPER, 180, 3, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 180, 3, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 182, 3, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 186, 3, 0},

		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 180, 3, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 182, 3, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 184, 3, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 186, 3, 0},

		{(int)ZOMBIE_INSTRUCTION_TYPE::WAIT, 220, 0, 0},

		// in-between stream
		{(int)ZOMBIE_INSTRUCTION_TYPE::CONEHEAD, 200, 3, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NEWSPAPER, 200, 0, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 200, 3, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::CONEHEAD, 230, 1, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::BUCKETHEAD, 230, 3, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NEWSPAPER, 250, 1, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 250, 1, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::CONEHEAD, 250, 0, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 250, 0, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::CONEHEAD, 280, 4, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::WAVE_CHKPOINT, 310, 0, 0},

		// final wave

		{(int)ZOMBIE_INSTRUCTION_TYPE::CONEHEAD, 340, 0, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 342, 0, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NEWSPAPER, 344, 3, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 346, 3, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 348, 3, 0},

		{(int)ZOMBIE_INSTRUCTION_TYPE::FLAG, 340, 1, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::CONEHEAD, 342, 1, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 344, 1, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NEWSPAPER, 346, 3, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 348, 3, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 350, 3, 0},

		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 340, 2, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NEWSPAPER, 342, 2, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::BUCKETHEAD, 344, 2, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 346, 3, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 348, 3, 0},

		{(int)ZOMBIE_INSTRUCTION_TYPE::NEWSPAPER, 340, 3, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 342, 3, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::CONEHEAD, 344, 3, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 346, 3, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 348, 3, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 350, 3, 0},

		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 340, 4, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::BUCKETHEAD, 340, 4, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::CONEHEAD, 340, 4, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 340, 3, 0},
		{(int)ZOMBIE_INSTRUCTION_TYPE::NORMAL, 340, 3, 0},

		// TODO: we need third wave.
	};

	const string LEVEL_10_MSG_BITMAP = "Resources/Background/Level Up/BMP/Level2-5.bmp";

	class Level10 : public Map
	{
	public:
		Level10() : Map(Level_10_zombie_instruction, LEVEL_10_MSG_BITMAP, false) {};

		~Level10() {};

	protected:
		int getPreviousLevel() { return LEVEL_9; }
		int getCurrentLevel() { return LEVEL_10; }
		int getNextLevel() { return MENU_BTN; }
	};

}